### ISSUE TITLE
Feature request - start & stop & control rate of spammer via API 

### ISSUE THREAD

**Issue by dnck** [HelixNetwork/pendulum#125]
Currently, the only way to start, stop, and control the rate of the Spammer is through the configuration setting, SPAM_DELAY.

This makes it such that the node can not start spamming without being shut-down, and restarted. 

Additionally, the rate of spam stays constant through the life of the node. 

This is a feature request to be able to control the Spammer through simple API calls. Ideally, we would be able to turn on the spammer, turn it off, and tune its rate. 

I have a version of this working in my fork ctps branch working through API calls to the startSpamming and stopSpamming endpoint. 

If approved, I could submit a pull request for these features to the dev branch.

**Comment by dnck** [comment]
The spammer was removed. Shall we close this?

**Comment by oliverfn** [comment]
> The spammer was removed. Shall we close this?

yep :)
