### ISSUE TITLE
File "log.name_IS_UNDEFINED" gets created during compilation 

### ISSUE THREAD

**Issue by dnck** [HelixNetwork/pendulum#180]
## Expected behavior

Compiling the src into target does not leave behind waste files. 

## Current behavior 

Compile with ```mvn clean compile package``` creates a log file in the root of the project, "log.name_IS_UNDEFINED".

## Failure info

May have been introduced by commit, 
https://github.com/HelixNetwork/pendulum/commit/5559b82b1d7e867dbe1f822e7ba25cc7918a442b

But, I am not totally sure. 

## Steps to reproduce 
Compile the src?

**Comment by spangin** [comment]
The file can be ignored.
If you don't like to see this file, we can use only console for info/debug messages during unit-tests working.
Is this solution OK?
