### ISSUE TITLE
Implement non-blocking transaction confirmation

### ISSUE THREAD

**Issue by dzhelezov** [HelixNetwork/pendulum#190]
Currently a transaction is confirmed only when a round becomes solid. Replace with 2/3+ milestone confirmations.

**Comment by oliverfn** [comment]
Currently, to get the confirmation state, [`getInclusionStatesStatement`](https://github.com/HelixNetwork/pendulum/blob/dev/src/main/java/net/helix/pendulum/service/API.java#L683) is used. The check evaluates  to true if a transaction.snapshotIndex() has been set.  As you say, this requires the respective round, from which a snap was created, to solidify and the snapshot to include the transaction in question.  


`getInclusionStatesStatement` will be refactored to: `getInclusionStatesStatementObsolete` (to temporarily preserve the functionality)

The 2/3rd majority check will be implemented in: `getInclusionStatesStatement`.

It would be desirable to refactor `getInclusionStates` to `getConfirmationState` as soon as possible, but we might not want to touch the command names _just yet_, as it would also require refactoring in sdk and wallet.

**Comment by oliverfn** [comment]
addressed in: https://github.com/HelixNetwork/pendulum/pull/206
