### ISSUE TITLE
If Validator.key exists Node will always start as a Validator regardless of startup flag/settings

### ISSUE THREAD

**Issue by oliverfn** [HelixNetwork/pendulum#196]
# Current Behavior
As soon as a valid `Validator.key` exists (in the resources dir) the node always starts as a validator, even if `--validator` is not explicitly set.
https://github.com/HelixNetwork/pendulum/blob/dev/src/main/java/net/helix/pendulum/Main.java#L138

# Expected Behavior
Even if `Validator.key` exists the `--validator` startup flag should still be required, _but_ without having to pass the path to the seed.

- initial startup of a validator should be: `--validator <PathToSeed>` (validator.key is created)
- node is allowed to enter validator routine if key matches hardcoded validator public key
- if a host owns a valid validator.key, _but_ starts without `--validator` setting, the node should follow the standard routine
- if a host owns a valid validator.key (located in resources dir), _but_ starts with `--validator` setting, **no** `<PathToSeed>` should be required anymore
- if a host owns a valid validator.key, but it is not located in the predefined directory (ie resources), the `--validator` setting should ideally also accept `<PathToValidatorKey>`.

**Comment by cristina-vasiu** [comment]
Flag --validator can not be used without value (only boolean parameters are allowed to not have any value), if we want to use a parameter without any value we have to change its name.
We should than have --validator (to show that a node is validator)
And --validatorSeedPath (to give path to validator seed file)
And maybe --validatorKeyPath (to change default key location)

**Comment by oliverfn** [comment]
> Flag --validator can not be used without value (only boolean parameters are allowed to not have any value), if we want to use a parameter without any value we have to change its name.
> We should than have --validator (to show that a node is validator)
> And --validatorSeedPath (to give path to validator seed file)
> And maybe --validatorKeyPath (to change default key location)

**Another suggestion**:
- `--validator` is boolean that indicates whether a node is validator. If seed and/or keyfile are in resources dir, the files are automatically detected / created.
- we add only one other setting: `--validator-path`: we detect in the code if the path ends with .key or .txt ending and imply whether its a seed or a keyfile.  (not sure this would be real efficient).

**otherwise**:
- `--validator-seed-path` and `--validator-key-path` seems fine too, as long as `--validator` can work by itself, if the file(s) are moved to resources
